# ColibrDB Documentation Site
# GitHub Pages configuration

title: ColibrDB
description: Un RDBMS sperimentale ad alte prestazioni scritto in Swift 6.2
baseurl: "/Colibri-DB"
url: "https://gpicchiarelli.github.io"

# Jekyll configuration
markdown: kramdown
highlighter: rouge
theme: minima

# GitHub Pages specific settings
github: [metadata]

# Defaults
defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# Collections
collections:
  docs:
    output: true
    permalink: /:collection/:name/

# Exclude files
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - .git
  - .gitignore
  - Sources/
  - Tests/
  - Examples/
  - .github/
  - Package.swift
  - Package.resolved
  - colibridb.conf.json
  - update_wiki.sh
  - create_wiki.py
  - create_wiki_curl.sh
