# ColibrDB Documentation Site
# GitHub Pages configuration

title: ColibrDB
description: Un RDBMS sperimentale ad alte prestazioni scritto in Swift 6.2
author: ColibrDB Team
url: https://gpicchiarelli.github.io
baseurl: /Colibri-DB

# Jekyll configuration
markdown: kramdown
highlighter: rouge
theme: minima

# GitHub Pages specific settings
github: [metadata]

# Collections
collections:
  docs:
    output: true
    permalink: /:collection/:name/

# Defaults
defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
  - scope:
      path: ""
      type: "docs"
    values:
      layout: "doc"

# Plugins
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

# Exclude files
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - .git
  - .gitignore
  - Sources/
  - Tests/
  - Examples/
  - .github/
  - Package.swift
  - Package.resolved
  - colibridb.conf.json
  - update_wiki.sh
  - create_wiki.py
  - create_wiki_curl.sh

# Social links
social:
  name: ColibrDB
  links:
    - https://github.com/gpicchiarelli/Colibri-DB
    - https://github.com/gpicchiarelli/Colibri-DB/issues
    - https://github.com/gpicchiarelli/Colibri-DB/discussions

# SEO
seo:
  type: Organization
  name: ColibrDB
  description: Un RDBMS sperimentale ad alte prestazioni scritto in Swift 6.2
  url: https://gpicchiarelli.github.io/Colibri-DB
  twitter:
    username: colibridb
