# Configurazione semplificata per GitHub Pages
title: "Colibrì DB"
description: "RDBMS professionale per macOS con architettura modulare e verifiche formali complete"
baseurl: "/Colibri-DB"
url: "https://gpicchiarelli.github.io"

# Build settings
markdown: kramdown
highlighter: rouge

# Collections
collections:
  wiki:
    output: true
    permalink: /wiki/:name/

# Defaults
defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
  - scope:
      path: ""
      type: "wiki"
    values:
      layout: "doc"

# Plugins (solo quelli supportati da GitHub Pages)
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# Exclude
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - vendor/
  - node_modules/
  - package.json
  - package-lock.json
  - .gitignore
  - .git/
  - .github/
